language: csharp

mono:
    - 3.10.0
    - 3.8.0
    - 3.2.8

# These commands simulate having a graphical display, which is needed
# for our GUI tests.
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
    - sudo apt-get install mono-devel nunit-console libtest-most-perl libipc-system-simple-perl
    - mozroots --import --ask-remove
    - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
    - bin/build
    - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console --exclude=FlakyNetwork build/Tests/bin/Debug/CKAN.Tests.dll
    - prove  # Run all the tests in t/

deploy:
    provider: releases
    api_key:
        secure: AjwbRLStNJZb9hAOLfRLK85KlFo2q2Dr1NKCoDS4elek1nqSiOjL1hH0kDgUMx/PJqQVnFU8tbJPL30t9Pj7jcJhp0LhbbPipQE3TCSpafTneSEbdz5HT+OdghWCZhUhfs07wGNTFUwcAO4WBZ7wv1AnfdfogHdA5RMdykiIl38=
    file:
        - ckan.exe
        - netkan.exe
    on:
        repo: KSP-CKAN/CKAN
        tags: true
        mono: 3.10.0
        # all_branches needed as a workaround for travis-ci#1675
        all_branches: true

    # Any merge to master gets sent to
    # http://ckan-travis.s3-website-us-east-1.amazonaws.com/
    # 
    # At least, they used to... Travis seems grumpy if we have
    # more than one deploy stanza, and we want releases more.
    #
    # - provider: s3
    #   access_key_id: AKIAI5JWAEFPFK6GH3XA
    #   secret_access_key:
    #     secure: b0PPlD7auqysK2LHA8N1US03dE/VKH2rOTwIqpIh50l/gURuXEl7Nd8S7qlf2dpEmz+8D5pIWD+J9scfrdD8Uuakhi3sQbqcV26UiR6+Ye06eGQfmIzqzAECt2naqEy7VJ/xrqq5aaaf8QhcOQMba3qVvwDSzkB2fJeh7+D6EY8=
    #   bucket: ckan-travis
    #  local-dir: uploads
    #   acl: public_read
    #  skip_cleanup: true
    #  on:
    #    repo: KSP-CKAN/CKAN
    #    all_branches: true
