language: c
install:
- sudo apt-get install mono-devel mono-gmcs nunit-console
- mozroots --import --ask-remove
script:
- cd CKAN
- xbuild CKAN.sln
- nunit-console Tests/bin/Debug/Tests.dll
before_deploy:
- cd ..
- mkdir uploads
- bin/build
- cp ckan.exe uploads/ckan-`git describe --long`.exe
deploy:
    provider: releases
    api_key:
        secure: AjwbRLStNJZb9hAOLfRLK85KlFo2q2Dr1NKCoDS4elek1nqSiOjL1hH0kDgUMx/PJqQVnFU8tbJPL30t9Pj7jcJhp0LhbbPipQE3TCSpafTneSEbdz5HT+OdghWCZhUhfs07wGNTFUwcAO4WBZ7wv1AnfdfogHdA5RMdykiIl38=
    file: ckan.exe
    on:
        repo: KSP-CKAN/CKAN
        tags: true
        all_branches: true

